[package]
name = "system-parachains-constants"
description = "Common constants for System Parachains runtimes"
repository.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
smallvec = "1.8.0"

frame-support = { default-features = false , version = "25.0.0" }
parachains-common = { default-features = false , version = "4.0.0" }
polkadot-core-primitives = { default-features = false, version = "4.0.0"}
polkadot-primitives = { default-features = false , version = "4.0.0" }
paseo-runtime-constants = { path = "../../relay/paseo/constants", default-features = false}
sp-runtime = { default-features = false , version = "28.0.0" }

[features]
default = [ "std" ]
std = [
	"frame-support/std",
	"parachains-common/std",
	"polkadot-core-primitives/std",
	"polkadot-primitives/std",
	"paseo-runtime-constants/std",
	"sp-runtime/std",
]
